# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# branches to build
branches:
  # whitelist
  only:
    - master

# build version format
version: "{build}"

# what combinations to test
environment:
  matrix:
    - nodejs_version: 0.10

# Get the stable version of node
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

matrix:
  fast_finish: true

cache:
  - C:\Users\appveyor\AppData\Roaming\npm\node_modules -> package.json  # global npm modules
  - C:\Users\appveyor\AppData\Roaming\npm-cache -> package.json         # npm cache
  - node_modules -> package.json                                        # local npm modules
